### ISSUE TITLE
Idea of an alternative to adding the OCR to a new field

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [cfculhane/AnkiOCR#1]
Hi,

I have been thinking about doing an addon like this for a while. Congrats for doing this!

I had another approach though that you might find interesting.

I really didn't like the idea to add OCR fields to all the note types that can contain text so my idea was instead to add the text content as an HTML comment in the field containing the picture. Visually, it does not change a thing to the card and is searchable through the anki browser. I also mean you can restrict search per field, as sometimes my pictures are added in "sources" field or in "More", "Cloze body" etc.

I think this could be a very interesting feature to add. What do you think? It would be worth asking Damien if it is reasonnable to do or if comments are sometimes cleaned up or whatever.

Another possibility was to add the text content in the "alt" argument of the "img" html attribute, like in [this example](https://www.w3schools.com/TAGS/att_img_alt.asp) But  I barely know HTML and have no idea what kind of issues this could create.

What do you think?

Either way the content would need to start with some kind of identifier like `___ocrtext_unixtime=23094203984209___` and `___endOCRtext___` to avoid adding text over and over in case someone runs the script regularly or wants to edit tesseract settings. At least that's how I designed it.

**Comment by Laern2Do** [comment]
I second that notion and i think it would be really cool, i also dont like how it create a new field. for user friendly sake, it would be nice if I can right-click on an image and create an OCR for that image in html with the alt argument. to further this point, may be made it automate if the user selected a specific note type (e.g., image occlusion) in config setting?

using OCR to make image contents search feasible is definitely a neat and useful idea :). kudos

**Comment by cfculhane** [comment]
These are great ideas, thanks for the suggestions! I initially had planned to just put the text in the 'Extra' field with small font, but of course not all cards have that field. Doing it the the img alt text is a really good option, I'll do some testing, but that might be the best way forward. Significantly less change of database stuff ups too!

**Comment by thiswillbeyourgithub** [comment]
Good to know I was a bit helpful :) 

I think it would be good to ask Damien's opinion on the forum, to be sure there are no limits somewhere to the alt field or whatever. Just to make sure there are no surprises you know.

**Comment by cfculhane** [comment]
![https://raw.githubusercontent.com/cfculhane/AnkiOCR/master/docs/text_tooltip.png](https://raw.githubusercontent.com/cfculhane/AnkiOCR/master/docs/text_tooltip.png)

How does this look? Putting in the 'title' attr means it comes up as a tooltip when hovering over the image

**Comment by cfculhane** [comment]
Closing this, as of V0.3.0 this is now the default method

**Comment by thiswillbeyourgithub** [comment]
klqjsfjqskdjfqsmkldjfqlsmkjfqksmjfqslkmfjqsmlfkqsjdflmkj should pretty much sum up my excitement.

Thanks a lot!
