### ISSUE TITLE
issue with the new version

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [cfculhane/AnkiOCR#10]
Hi,

Sorry to be the bearer of bad news.
The new version doesn't seem to work all that well. As with the previous version the gui completely freezes when running OCR, so I can't really know if it's progressing or not on large collection. But overall this seems WAY slower than before. I tried lowering the batch size to 1 to try and see if it worked better but it didn't change a thing.

I am pretty sure it just runs in circle at some point when I scan more than 2 batches at once but I can't know if the progress bar doesn't appear.

It would be great to have the progress bar work. This way we could also have a "cancel" button, otherwise I had to force quit anki and manually kill each tesseract process.

Displaying the time it took to run at the end would be helpful too to organize myself when I want to scan a huge deck but that is minor.

System : ubuntu 18 with anki 2.1.35

**Comment by thiswillbeyourgithub** [comment]
Sorry but for some reason it seems to work flawlessly now, I didn't change a thing and didn't even restarted anki. Well I'll come back here if I have more information.

But something still feels wrong about the progress bar, it doesn't update often enough and there is no way to cancel.

**Comment by cfculhane** [comment]
Thanks for your feedback - I'm a little confused as to how to implement a good way of cancelling, I'm not used to interacting with the QT GUI framework, but ill look into it, as I have noted the same problem. 

Re: batching, I may have set the default batch size (20) too high. 

Re: progress bar - this is I think mostly placebo effect, as I'm not batching, I am only updating the progress bar as each batch of 20 comes through, giving the appearance of a slower updating bar. I will try lowering the default batch size, and this should help improve things. Will also add a timer thingo to the end, that's a great idea!

**Comment by cfculhane** [comment]
After some further testing i've reduced the default batch size to 5, it makes the whole thing feel much more responsive (and is slightly quicker for smaller batches too)

**Comment by cfculhane** [comment]
Have now implemented a way of cancelling, takes a second or two to cancel all the threads but works really well! :) 

![image](https://user-images.githubusercontent.com/40076371/103435459-d80a6d00-4c62-11eb-84e2-1e9058fece97.png)


![image](https://user-images.githubusercontent.com/40076371/103435452-c7f28d80-4c62-11eb-89f5-5f875e6f6e96.png)

**Comment by cfculhane** [comment]
Have pushed a new release, thanks for the feedback!

**Comment by thiswillbeyourgithub** [comment]
Hello again

>  thanks for the feedback!

Here's another one :)  

I just tried running a batch of 148 cards with batch size of 5 and it hangs. The UI freezes, no progress bar in about 5 minutes so no way of cancelling, all cpus at 100% of course. My computer is quite powerful so it's not the issue.

If the multithreading proves to be an issue on some setup you might want to add an option to toggle it, depending on how you coded the batch it could be easy to implement.

edit : after about 10/15 minutes I now see the progress bar window, at 4%. So 148 cards in batches of five means that indeed I only finished 1 batch.

Don't know if it's related but htop shows me 12 tesseract process and I'm not sure it's the right number of threads for my computer. Maybe allowing the user to specify himself the number of threads would be a good idea, it might (no idea) solve my issue and allows to toggle or not multithreading in a way. I think I have something like a 4 core cpu that can somehow appear as 8 using some fancy intel thingy. 12 seems unusual though.

**Comment by cfculhane** [comment]
Interesting, I am processing rougly 10 images per second on my 10 year old
i5 quad core!

I think there may be something funky going on. Yeah I can fairly easily
make it toggle, or allow the user to set the num of threads. I'll have a
play tomorrow and get back to you!

**Comment by thiswillbeyourgithub** [comment]
Nice!

If you don't know what's the issue maybe you could make me a test version that shows all the timers, because curently if I select about 5 cards I have a minimum of 0.5s per note but I got up to 2s per note when I selected 17 cards. I don't know what steps is making that so long.

Btw. If I'm not mistaken multithreading by batch is activated as soon as you try to OCR more than 5 cards, I'm note sure that's optimal. Maybe you should activate multithreading only if the user tries to OCR 20+ cards or something, otherwise lots of cpu is used just to setup the parallelization. I think. I know next to nothing about cpu anyway but just my 2cnt.

**Comment by cfculhane** [comment]
![image](https://user-images.githubusercontent.com/40076371/103452738-a955ca80-4d26-11eb-9645-505fcdaeba4e.png)


Heres some timing results on my pc for 200 images, just OCRing the images.

Are you able to pull the `master` branch and run `test_peformance` in a console or from the command line? You should be able to get a printout similar to the above

**Comment by thiswillbeyourgithub** [comment]
There you go

![screenshot](https://user-images.githubusercontent.com/26625900/103459960-82899b00-4d0a-11eb-93ab-ab3f213ed7c4.png)

**Comment by cfculhane** [comment]
Thanks for that! interesting that your multi-threaded performance is so much worse, there's something funky going on here - your single threaded performance is slightly better than mine, but your multithreaded is 4x slower than single! I'll push a new release that has options for setting the number of threads for those use cases like this where the performance is worse.

**Comment by thiswillbeyourgithub** [comment]
Thanks!

I will try to run the test with "num_threads=2" to see if that helps my case.

**Comment by thiswillbeyourgithub** [comment]
edit : I reran the script (albeit on only 50 images) with num_threads=2 then =4 again.

with 2 : 
```
All done, timing results: 

time_batched_single = 33.71 s | 0.58 s per image
time_batched_multi = 15.76 s | 0.27 s per image
time_unbatched_single = 36.54 s | 0.63 s per image
time_unbatched_multi = 17.0 s | 0.29 s per image
```


with 4 : 
```
All done, timing results: 

time_batched_single = 31.01 s | 0.53 s per image
time_batched_multi = 133.47 s | 2.3 s per image
time_unbatched_single = 43.4 s | 0.75 s per image
time_unbatched_multi = 133.49 s | 2.3 s per image
```


So indeed, it is slower with 4 instead of 2. But I noticed that my linux stated that 4 threads where running in the terminal while I remember seeing 12 when running ankiOCR in anki directly. Maybe my laptop has some fancy cpu features that allows to appear as more or less core to be ready. Hence explaining why I seemed to get inconsistent speed using anki. Go figure.

A solution seems to be to specify the number of threads directly.

**Comment by cfculhane** [comment]
This is fixed as of the latest release in https://github.com/cfculhane/AnkiOCR/commit/66db6dccef763cb6eed18897e19cac0ed45391d7 

It now defaults to two threads, and allows config of num threads as well as disabling the batching and multithreading

**Comment by thiswillbeyourgithub** [comment]
Great, thanks!

**Comment by thiswillbeyourgithub** [comment]
Arg, sorry for the double mail. It appears the addon is not functionnal.

I just updated it and can't access the config panel, it says `Add-on has no configuration.`

When trying to run the addon on a few images I get this error message :

```
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.35 (84dcaa86) Python 3.8.1 Qt 5.15.1 PyQt 5.15.1
Platform: Linux
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-01-18 19:20:21
Add-ons possibly involved: ⁨AnkiOCR⁩

Caught exception:
Traceback (most recent call last):
  File "/home/USER/.local/share/Anki2/addons21/450181164/gui.py", line 108, in <lambda>
    act_run_ocr.triggered.connect(lambda b=browser: on_run_ocr(browser))
  File "/home/USER/.local/share/Anki2/addons21/450181164/gui.py", line 24, in on_run_ocr
    num_batches = ceil(num_notes / config["batch_size"])
TypeError: 'NoneType' object is not subscriptable
```

**Comment by cfculhane** [comment]
Arghh yeah, not sure quite what broke, will fix tonight :(

**Comment by cfculhane** [comment]
Fixed in 0.4.3

**Comment by thiswillbeyourgithub** [comment]
Seems to work great!

Thanks a lot!!!

**Comment by cfculhane** [comment]
So annoying was literally just a last minute change I made to sort the
config.json so that it would appear jn the same order as the gui, but one
line was missing a comma :(
