### ISSUE TITLE
Incompatibility with clozes

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [cfculhane/AnkiOCR#12]
Hi,

Just a quick heads up to point out that if an image contains "::" in the text, it will break clozes as it will appear as a hint.

Not sure of how to best handle this case though.

Have a nice day!

**Comment by cfculhane** [comment]
This is an easy fix, I'm doing some post processing on the text anyway, so
I'll push a new version out today with this and the multithreading options!

Thanks for the handy bug report!

**Comment by cfculhane** [comment]
Sorry didn't get to this today, will push an update soon

**Comment by cfculhane** [comment]
This is fixed as of https://github.com/cfculhane/AnkiOCR/commit/66db6dccef763cb6eed18897e19cac0ed45391d7 , and I added a test for it as well :)
