### ISSUE TITLE
AnkiOCR should ignore links

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [cfculhane/AnkiOCR#15]
Hi,

I noticed a very annoying issue. Sometimes an image is not really in collection.media but is actually a link to an image, that anki fetches.

When you have a card like that and run AnkiOCR on a large collection that includes it, it will go through all the selected cards then show a cryptic error and most importantly won't save any of the OCR'd cards that have not faileed.

To solve those issues I have to read the error, then find the card that uses this image, then manually use an image instead of a link, then re run OCR on all the cards.

I think AnkiOCR should at least ignore the links, or fetch the image and OCR it then store the plaintext as usual without saving the media.

In any case, is there no way to not have done the OCR for nothing? It can take quite come time to run.

Here's the error message : 
> Cancelled OCR processing with message : 
> ['Traceback (most recent call last):\n', '  File "/home/USERNAME/.local/share/Anki2/addons21/450181164/gui.py", line 54, in on_run_ocr\n    ocr.run_ocr_on_notes(note_ids=selected_nids)\n', '  File "/home/USERNAME/.local/share/Anki2/addons21/450181164/ocr.py", line 303, in run_ocr_on_notes\n    notes_query = self.run_ocr_on_query(query=query_str)\n', '  File "/home/USERNAME/.local/share/Anki2/addons21/450181164/ocr.py", line 272, in run_ocr_on_query\n    raw_results = self._ocr_batch_process(batched_txts=batched_txts)\n', '  File "/home/USERNAME/.local/share/Anki2/addons21/450181164/ocr.py", line 94, in _ocr_batch_process\n    raw_results[batched_img_txt] = future.result()\n', '  File "concurrent/futures/_base.py", line 432, in result\n', '  File "concurrent/futures/_base.py", line 388, in __get_result\n', '  File "concurrent/futures/thread.py", line 57, in run\n', '  File "/home/USERNAME/.local/share/Anki2/addons21/450181164/ocr.py", line 259, in _ocr_img\n    return pytesseract.image_to_string(str(img_pth), lang="+".join(languages or ["eng"]))\n', '  File "/home/USERNAME/.local/share/Anki2/addons21/450181164/_vendor/pytesseract/pytesseract.py", line 368, in image_to_string\n    return {\n', '  File "/home/USERNAME/.local/share/Anki2/addons21/450181164/_vendor/pytesseract/pytesseract.py", line 371, in <lambda>\n    Output.STRING: lambda: run_and_get_output(*args),\n', '  File "/home/USERNAME/.local/share/Anki2/addons21/450181164/_vendor/pytesseract/pytesseract.py", line 280, in run_and_get_output\n    run_tesseract(**kwargs)\n', '  File "/home/USERNAME/.local/share/Anki2/addons21/450181164/_vendor/pytesseract/pytesseract.py", line 257, in run_tesseract\n    raise TesseractError(proc.returncode, get_errors(error_string))\n', "450181164._vendor.pytesseract.pytesseract.TesseractError: (1, 'Tesseract Open Source OCR Engine v4.0.0-beta.1 with Leptonica Error in fopenReadStream: file not found Error in pixRead: image file not found: /home/USERNAME/.local/share/Anki2/Main/collection.media/https:/www.i-scanimaging.com/fileadmin/_processed_/1/d/preview_eea8daa970_113904783.jpg Image file /home/USERNAME/.local/share/Anki2/Main/collection.media/https:/www.i-scanimaging.com/fileadmin/_processed_/1/d/preview_eea8daa970_113904783.jpg cannot be read! Error during processing.')\n"]

Thanks!

**Comment by cfculhane** [comment]
Thanks for this bug report (and apologies for the delay, I'm now deep into third year med school so my time has evaporated!), I'll fix this today and get a result out. 

I'm a little wary about fetching links given their might be security implications, but I can definitely check for links and ignore them, possibly adding a warning text listing the card(s) that had links I didn't parse.

**Comment by cfculhane** [comment]
![image](https://user-images.githubusercontent.com/40076371/109384399-90d9e900-7940-11eb-81b2-fe2479e2f0db.png)

This was a good excuse to add better handling of logging to the addon. Now if any logger messages of warning or higher are raised during processing, they will be shown in the final message.
