### ISSUE TITLE
You might be interested in learning easyOCR exists

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [cfculhane/AnkiOCR#2]
https://github.com/JaidedAI/EasyOCR

I think it can be useful to make the installation process easier for less techy users. Never used it though.

edit : just saw on reddit that you knew this already. The second link still stands though

**Comment by thiswillbeyourgithub** [comment]
Also, in case you didn't know : https://github.com/madelesi/anki_ocr

**Comment by cfculhane** [comment]
Thanks, I did have a look at EasyOCR, the results were slightly better than Tesseract if anything, however its actually harder to package. It depends on `torch` and `torchvision`, both libraries with lots of different versions, dependencies that make its very difficult to package with an anki addon (we don't have access to `pip`).
