### ISSUE TITLE
Cancled OCR, Image Not Found (Image Occlusion Card)

### ISSUE THREAD

**Issue by wolphboy007** [cfculhane/AnkiOCR#28]
OCR failed on my image occlusion cards. I'm running Anki Version ⁨2.1.39 (576f0043)⁩. See error message below and attached [screenshot:](url)

Cancelled OCR processing with message : 
['Traceback (most recent call last):\n', '  File "/Users/justinbrandt/Library/Application Support/Anki2/addons21/450181164/gui.py", line 58, in on_run_ocr\n    ocr.run_ocr_on_notes(note_ids=selected_nids)\n', '  File "/Users/justinbrandt/Library/Application Support/Anki2/addons21/450181164/ocr.py", line 308, in run_ocr_on_notes\n    notes_query = self.run_ocr_on_query(note_ids=note_ids)\n', '  File "/Users/justinbrandt/Library/Application Support/Anki2/addons21/450181164/ocr.py", line 278, in run_ocr_on_query\n    raw_results = self._ocr_batch_process(batched_txts=batched_txts)\n', '  File "/Users/justinbrandt/Library/Application Support/Anki2/addons21/450181164/ocr.py", line 96, in _ocr_batch_process\n    raw_results[batched_img_txt] = future.result()\n', '  File "concurrent/futures/_base.py", line 432, in result\n', '  File "concurrent/futures/_base.py", line 388, in __get_result\n', '  File "concurrent/futures/thread.py", line 57, in run\n', '  File "/Users/justinbrandt/Library/Application Support/Anki2/addons21/450181164/ocr.py", line 264, in _ocr_img\n    return pytesseract.image_to_string(str(img_pth), lang="+".join(languages or ["eng"]),\n', '  File "/Users/justinbrandt/Library/Application Support/Anki2/addons21/450181164/_vendor/pytesseract/pytesseract.py", line 368, in image_to_string\n    return {\n', '  File "/Users/justinbrandt/Library/Application Support/Anki2/addons21/450181164/_vendor/pytesseract/pytesseract.py", line 371, in <lambda>\n    Output.STRING: lambda: run_and_get_output(*args),\n', '  File "/Users/justinbrandt/Library/Application Support/Anki2/addons21/450181164/_vendor/pytesseract/pytesseract.py", line 280, in run_and_get_output\n    run_tesseract(**kwargs)\n', '  File "/Users/justinbrandt/Library/Application Support/Anki2/addons21/450181164/_vendor/pytesseract/pytesseract.py", line 257, in run_tesseract\n    raise TesseractError(proc.returncode, get_errors(error_string))\n', "450181164._vendor.pytesseract.pytesseract.TesseractError: (-6, 'dyld: Library not loaded: ../../../leptonica/1.80.0/lib/liblept.5.dylib   Referenced from: /Users/justinbrandt/Library/Application Support/Anki2/addons21/450181164/deps/mac/tesseract/4.1.1/bin/tesseract   Reason: image not found')\n"]

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/38637136/133670642-736ffb99-7baf-44af-b53d-945d49eae39f.png">

**Comment by cfculhane** [comment]
Hi, are you able to display the filename of the image (by pressing Control-Shift-X (Command-Shift-X) while the cursor is in the image field? This is seems to be the same issue as #27 , and I can't figure out why!

**Comment by cfculhane** [comment]
Attempted a fix - https://github.com/cfculhane/AnkiOCR/releases/tag/V0.6.1 , please restart anki and check for updates of the plugin and try again :)

**Comment by cfculhane** [comment]
Fixed in https://github.com/cfculhane/AnkiOCR/releases/tag/V0.7.0 , please reopen if you have any further issues with this
