### ISSUE TITLE
Doesn't find Tesseract-ocr

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [cfculhane/AnkiOCR#3]
Hi,
I followed the instructions carefully and installed tesseract-ocr, libtesseract-dev, language pack and even the snap version but it still doesn't work. I am on Linux ubuntu 18.04.

I get the message `processed for X cards` when there are no imgs in the card but when there is an image I get the error : `Could not find a valid Tesseract-OCR installation! 
Please visit the addon page in at https://ankiweb.net/shared/info/450181164 for install instructions`

Can you tell me where I can find logs ? I have a decent chance of solving this myself if I can get them, to avoid bothering you.

**Comment by thiswillbeyourgithub** [comment]
edit : I also noticed the path was wrong : `which tesseract` returns `/usr/bin/tesseract`, without "local".

Changing this doesn't solve my issue though.

Installing pytesseract via pip3 either.

**Comment by cfculhane** [comment]
Thanks for giving it a try, I might expose the path to the directory for edge cases like this - I don't have a Linux distro installed at the moment to attempt this, but would that help? Logs aren't currently being written, but I can start writing them, maybe via a debug flag in the config, that might help too. I'm a bit snowed under with med school and work, might not get to this until later in the week.

**Comment by thiswillbeyourgithub** [comment]
Thanks for answering quickly. If you're not already familiar with linux I don't think it will be an efficient way to solve this than to make you install it.

I think logs will be useful, but I might eventually figure it out on my own. Maybe some other users will chime in with helpful information.

Nice to see a felow med schooler doing coding ;).

**Comment by cfculhane** [comment]
Reasonably familiar, at work we code on an AWS ubuntu instance, so I'm becoming a little more familiar, but don't use it day to day on my personal computer yet. Will update this issue when some more changes are made 👍

**Comment by rogershijin** [comment]
I'm on Arch and I also had this problem, adding a symlink fixed it.

`ln -s /usr/bin/tesseract /usr/local/bin/tesseract`

**Comment by cfculhane** [comment]
So i've update this to default the path in Linux installs to `/usr/bin/tesseract` , and leaving MacOS as `/usr/local/bin/tesseract`. 

Additionally, I've added config variables for `override_tesseract_exec` (boolean) and `teseract_exec_dir` (path to directory), so if users want to customise where it's looking, it can do so.
