### ISSUE TITLE
preserving layout

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [cfculhane/AnkiOCR#4]
Hi,

I was curious as to if you tried to keep layout when OCRing the image.

I find [information on the internet that gives me hope that it's possible](https://stackoverflow.com/questions/22609778/how-to-preserve-document-structure-in-tesseract)

I don't need this myself I think but I can imagine people asking for this.

I would gladly do a PR if I managed to pull it off but I can't make your addon work for now.

**Comment by cfculhane** [comment]
Thanks for this, definitely a stretch goal as this addon was originally intended just gather text for card searchability. That said, it would definitely make the addon more useful.

I don't have a huge amount of time, hopefully, we can get your install working if you want to have a play.

**Comment by thiswillbeyourgithub** [comment]
Gladly!
