### ISSUE TITLE
Update to AnkiOCR to work for newer anki version

### ISSUE THREAD

**Issue by sogardoliver** [cfculhane/AnkiOCR#42]
would you consider updating the AnkiOCR add on for the newer anki versions?

**Comment by cfculhane** [comment]
This is now being worked on, fix is on master, will release this week :)  Closing this as it is better tracked in #45

**Comment by cfculhane** [comment]
This is now being worked on, fix is on master, will release this week :)  Closing this as it is better tracked in #45
